In [2]:
# Import Libraries
import pandas as pd
import numpy as np
import re

In [3]:
data_frame = pd.read_csv("articles.csv",encoding='latin1')

In [4]:
data_frame.head()

Id  \
0  d6995462-5e87-453b-b64d-e9f1df6e94d2   
1  8b05e939-a89e-4548-b92b-013822e8ee7d   
2  69fcd400-bceb-4255-8277-619f2d68ac0b   
3  17943578-c11b-414b-b3f5-063d3a93157b   
4  f33c7b11-5f77-4a98-bb2e-d36689042aea   

                                             Heading  \
0  A Puzzling Maneuver, Then Freefall: NTSB Repor...   
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...   
2                Bell Helicopter Show Air Taxi Nexus   
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...   
4             Les premiers retours d’Olivier Ezratty   

                                Article.Banner.Image                Outlets  \
0                                                NaN           Essex Caller   
1                                                NaN  Aviation Week Network   
2  http://images.tmtpost.com/uploads/images/2019/...                TMTPost   
3  http://www.fredzone.org/wp-content/uploads/201...               Fredzone   
4                                                NaN              FrenchWeb   

                                 Article.Description  \
0  <p>The helicopter that crashed in Southeast Al...   
1  <p>A year after teasing the fledgling electric...   
2  <p>Bell released the full-size design of the v...   
3  <p>Bell est une soci&eacute;t&eacute; am&eacut...   
4  <p>It was still anecdotal to observe the explo...   

                                        Full_Article Article_Type  Tonality  
0  <p>The helicopter that crashed in Southeast Al...   Commercial  Negative  
1  <p>A year after teasing the fledgling electric...   Commercial  Positive  
2  <p>Bell released the full-size design of the v...   Commercial  Positive  
3  <p>Bell est une soci&eacute;t&eacute; am&eacut...   Commercial  Positive  
4  <p>It was still anecdotal to observe the explo...   Commercial  Positive

In [5]:
# Removing HTML tags from Article.Description
def remove_tags(string):
    """
    This function is used to remove html tags in the string.
    Parameter : string
    return : string
    """
    result = re.sub('<.*?>','',string)
    return result

In [6]:
data_frame['Article.Description'] = data_frame['Article.Description'].apply(lambda cw : remove_tags(cw))

In [7]:
data_frame['Full_Article'] = data_frame['Full_Article'].apply(lambda cw : remove_tags(cw))

In [8]:
# Head of data frame after Removing HTML tags
data_frame.head()

Id  \
0  d6995462-5e87-453b-b64d-e9f1df6e94d2   
1  8b05e939-a89e-4548-b92b-013822e8ee7d   
2  69fcd400-bceb-4255-8277-619f2d68ac0b   
3  17943578-c11b-414b-b3f5-063d3a93157b   
4  f33c7b11-5f77-4a98-bb2e-d36689042aea   

                                             Heading  \
0  A Puzzling Maneuver, Then Freefall: NTSB Repor...   
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...   
2                Bell Helicopter Show Air Taxi Nexus   
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...   
4             Les premiers retours d’Olivier Ezratty   

                                Article.Banner.Image                Outlets  \
0                                                NaN           Essex Caller   
1                                                NaN  Aviation Week Network   
2  http://images.tmtpost.com/uploads/images/2019/...                TMTPost   
3  http://www.fredzone.org/wp-content/uploads/201...               Fredzone   
4                                                NaN              FrenchWeb   

                                 Article.Description  \
0  The helicopter that crashed in Southeast Alask...   
1  A year after teasing the fledgling electric ve...   
2  Bell released the full-size design of the vert...   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   
4  It was still anecdotal to observe the explosio...   

                                        Full_Article Article_Type  Tonality  
0  The helicopter that crashed in Southeast Alask...   Commercial  Negative  
1  A year after teasing the fledgling electric ve...   Commercial  Positive  
2  Bell released the full-size design of the vert...   Commercial  Positive  
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   Commercial  Positive  
4  It was still anecdotal to observe the explosio...   Commercial  Positive

In [9]:
# creating new column Preprocessed_Text
data_frame['Preprocessed_Text'] = data_frame['Heading'].astype(str) +" "+ data_frame['Article.Description'].astype(str) +" "+ data_frame['Full_Article'] 

In [10]:
# head of data frame after adding Preprocessed_Text column
data_frame.head()

Id  \
0  d6995462-5e87-453b-b64d-e9f1df6e94d2   
1  8b05e939-a89e-4548-b92b-013822e8ee7d   
2  69fcd400-bceb-4255-8277-619f2d68ac0b   
3  17943578-c11b-414b-b3f5-063d3a93157b   
4  f33c7b11-5f77-4a98-bb2e-d36689042aea   

                                             Heading  \
0  A Puzzling Maneuver, Then Freefall: NTSB Repor...   
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...   
2                Bell Helicopter Show Air Taxi Nexus   
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...   
4             Les premiers retours d’Olivier Ezratty   

                                Article.Banner.Image                Outlets  \
0                                                NaN           Essex Caller   
1                                                NaN  Aviation Week Network   
2  http://images.tmtpost.com/uploads/images/2019/...                TMTPost   
3  http://www.fredzone.org/wp-content/uploads/201...               Fredzone   
4                                                NaN              FrenchWeb   

                                 Article.Description  \
0  The helicopter that crashed in Southeast Alask...   
1  A year after teasing the fledgling electric ve...   
2  Bell released the full-size design of the vert...   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   
4  It was still anecdotal to observe the explosio...   

                                        Full_Article Article_Type  Tonality  \
0  The helicopter that crashed in Southeast Alask...   Commercial  Negative   
1  A year after teasing the fledgling electric ve...   Commercial  Positive   
2  Bell released the full-size design of the vert...   Commercial  Positive   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   Commercial  Positive   
4  It was still anecdotal to observe the explosio...   Commercial  Positive   

                                   Preprocessed_Text  
0  A Puzzling Maneuver, Then Freefall: NTSB Repor...  
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...  
2  Bell Helicopter Show Air Taxi Nexus Bell relea...  
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...  
4  Les premiers retours d’Olivier Ezratty It was ...

In [11]:
# Import stopwords with nltk.
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [12]:
data_frame['Preprocessed_Text'] = data_frame['Preprocessed_Text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

In [13]:
# head of data frame after removing Stop words
data_frame.head()

Id  \
0  d6995462-5e87-453b-b64d-e9f1df6e94d2   
1  8b05e939-a89e-4548-b92b-013822e8ee7d   
2  69fcd400-bceb-4255-8277-619f2d68ac0b   
3  17943578-c11b-414b-b3f5-063d3a93157b   
4  f33c7b11-5f77-4a98-bb2e-d36689042aea   

                                             Heading  \
0  A Puzzling Maneuver, Then Freefall: NTSB Repor...   
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...   
2                Bell Helicopter Show Air Taxi Nexus   
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...   
4             Les premiers retours d’Olivier Ezratty   

                                Article.Banner.Image                Outlets  \
0                                                NaN           Essex Caller   
1                                                NaN  Aviation Week Network   
2  http://images.tmtpost.com/uploads/images/2019/...                TMTPost   
3  http://www.fredzone.org/wp-content/uploads/201...               Fredzone   
4                                                NaN              FrenchWeb   

                                 Article.Description  \
0  The helicopter that crashed in Southeast Alask...   
1  A year after teasing the fledgling electric ve...   
2  Bell released the full-size design of the vert...   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   
4  It was still anecdotal to observe the explosio...   

                                        Full_Article Article_Type  Tonality  \
0  The helicopter that crashed in Southeast Alask...   Commercial  Negative   
1  A year after teasing the fledgling electric ve...   Commercial  Positive   
2  Bell released the full-size design of the vert...   Commercial  Positive   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   Commercial  Positive   
4  It was still anecdotal to observe the explosio...   Commercial  Positive   

                                   Preprocessed_Text  
0  A Puzzling Maneuver, Then Freefall: NTSB Repor...  
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...  
2  Bell Helicopter Show Air Taxi Nexus Bell relea...  
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...  
4  Les premiers retours d’Olivier Ezratty It stil...

In [14]:
# Function To remove Punctuations
import string
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text

In [15]:
data_frame['Preprocessed_Text'] = data_frame['Preprocessed_Text'].apply(remove_punctuations)

In [16]:
# head of data frame after removing Punctuations
data_frame.head()

Id  \
0  d6995462-5e87-453b-b64d-e9f1df6e94d2   
1  8b05e939-a89e-4548-b92b-013822e8ee7d   
2  69fcd400-bceb-4255-8277-619f2d68ac0b   
3  17943578-c11b-414b-b3f5-063d3a93157b   
4  f33c7b11-5f77-4a98-bb2e-d36689042aea   

                                             Heading  \
0  A Puzzling Maneuver, Then Freefall: NTSB Repor...   
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...   
2                Bell Helicopter Show Air Taxi Nexus   
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...   
4             Les premiers retours d’Olivier Ezratty   

                                Article.Banner.Image                Outlets  \
0                                                NaN           Essex Caller   
1                                                NaN  Aviation Week Network   
2  http://images.tmtpost.com/uploads/images/2019/...                TMTPost   
3  http://www.fredzone.org/wp-content/uploads/201...               Fredzone   
4                                                NaN              FrenchWeb   

                                 Article.Description  \
0  The helicopter that crashed in Southeast Alask...   
1  A year after teasing the fledgling electric ve...   
2  Bell released the full-size design of the vert...   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   
4  It was still anecdotal to observe the explosio...   

                                        Full_Article Article_Type  Tonality  \
0  The helicopter that crashed in Southeast Alask...   Commercial  Negative   
1  A year after teasing the fledgling electric ve...   Commercial  Positive   
2  Bell released the full-size design of the vert...   Commercial  Positive   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   Commercial  Positive   
4  It was still anecdotal to observe the explosio...   Commercial  Positive   

                                   Preprocessed_Text  
0  A Puzzling Maneuver Then Freefall NTSB Report ...  
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...  
2  Bell Helicopter Show Air Taxi Nexus Bell relea...  
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...  
4  Les premiers retours d’Olivier Ezratty It stil...

In [17]:
# Removing Trailing And Leading Spaces
data_frame['Preprocessed_Text'] = data_frame['Preprocessed_Text'].apply(lambda x: x.strip())

In [18]:
data_frame.head()

Id  \
0  d6995462-5e87-453b-b64d-e9f1df6e94d2   
1  8b05e939-a89e-4548-b92b-013822e8ee7d   
2  69fcd400-bceb-4255-8277-619f2d68ac0b   
3  17943578-c11b-414b-b3f5-063d3a93157b   
4  f33c7b11-5f77-4a98-bb2e-d36689042aea   

                                             Heading  \
0  A Puzzling Maneuver, Then Freefall: NTSB Repor...   
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...   
2                Bell Helicopter Show Air Taxi Nexus   
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...   
4             Les premiers retours d’Olivier Ezratty   

                                Article.Banner.Image                Outlets  \
0                                                NaN           Essex Caller   
1                                                NaN  Aviation Week Network   
2  http://images.tmtpost.com/uploads/images/2019/...                TMTPost   
3  http://www.fredzone.org/wp-content/uploads/201...               Fredzone   
4                                                NaN              FrenchWeb   

                                 Article.Description  \
0  The helicopter that crashed in Southeast Alask...   
1  A year after teasing the fledgling electric ve...   
2  Bell released the full-size design of the vert...   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   
4  It was still anecdotal to observe the explosio...   

                                        Full_Article Article_Type  Tonality  \
0  The helicopter that crashed in Southeast Alask...   Commercial  Negative   
1  A year after teasing the fledgling electric ve...   Commercial  Positive   
2  Bell released the full-size design of the vert...   Commercial  Positive   
3  Bell est une soci&eacute;t&eacute; am&eacute;r...   Commercial  Positive   
4  It was still anecdotal to observe the explosio...   Commercial  Positive   

                                   Preprocessed_Text  
0  A Puzzling Maneuver Then Freefall NTSB Report ...  
1  Bell’s Nexus Air Taxi Concept Rings Changes Fo...  
2  Bell Helicopter Show Air Taxi Nexus Bell relea...  
3  BELL DÉVOILE LA CONCEPTION INTÉGRALE DE SON TA...  
4  Les premiers retours d’Olivier Ezratty It stil...

In [19]:
# Feature Engineering and Classifier Model

In [20]:
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [92]:
text = data_frame['Preprocessed_Text']
y = data_frame['Article_Type']

In [93]:
# split the dataset into training and validation datasets 
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(text, y)

In [97]:
# label encode the target variable 
encoder = preprocessing.LabelEncoder()
encoder.fit(train_y)

LabelEncoder()

In [100]:
encoder_name_mapping = dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))

In [101]:
print(encoder_name_mapping)

{'Commercial': 0, 'Executives': 1, 'Military': 2, 'Others': 3, 'Support & Services': 4, 'Training': 5}


In [99]:
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

In [24]:
# create a count vectorizer object 
count_vect = CountVectorizer(analyzer='word', token_pattern=r'\w{1,}')
count_vect.fit(text)

CountVectorizer(token_pattern='\\w{1,}')

In [25]:
# transform the training and validation data using count vectorizer object
xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

In [26]:
# word level tf-idf
tfidf_vect = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', max_features=5000)
tfidf_vect.fit(text)
xtrain_tfidf =  tfidf_vect.transform(train_x)
xvalid_tfidf =  tfidf_vect.transform(valid_x)

In [27]:
def train_model(classifier, feature_vector_train, label, feature_vector_valid):
    # fit the training dataset on the classifier
    classifier.fit(feature_vector_train, label)
    
    # predict the labels on validation dataset
    predictions = classifier.predict(feature_vector_valid)
    
    return metrics.accuracy_score(predictions, valid_y)

In [28]:
# Naive Bayes on Word Level TF IDF Vectors
accuracy = train_model(naive_bayes.MultinomialNB(), xtrain_tfidf, train_y, xvalid_tfidf)
print ("NB, WordLevel TF-IDF: ", accuracy)
classifier = naive_bayes.MultinomialNB()

model = classifier.fit(xtrain_tfidf,train_y)

pred_y = model.predict(xvalid_tfidf)
results = confusion_matrix(valid_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(valid_y, pred_y)) 

NB, WordLevel TF-IDF:  0.914577530176416
Confusion Matrix :
[[589   0   0  33   0   0   0]
 [ 13   4   0   1   0   0   0]
 [  0   0   0   1   0   0   0]
 [ 24   0   0 392   0   0   0]
 [ 11   0   0   3   0   0   0]
 [  4   0   0   0   0   0   0]
 [  1   0   0   1   0   0   0]]
Accuracy Score : 0.914577530176416


In [29]:
# Linear Classifier on Word Level TF IDF Vectors
accuracy = train_model(linear_model.LogisticRegression(), xtrain_tfidf, train_y, xvalid_tfidf)
print ("LR, WordLevel TF-IDF: ", accuracy)
classifier = linear_model.LogisticRegression()

model = classifier.fit(xtrain_tfidf,train_y)

pred_y = model.predict(xvalid_tfidf)
results = confusion_matrix(valid_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(valid_y, pred_y))

LR, WordLevel TF-IDF:  0.9350046425255338
Confusion Matrix :
[[604   0   0  18   0   0   0]
 [  7  10   0   1   0   0   0]
 [  1   0   0   0   0   0   0]
 [ 25   0   0 391   0   0   0]
 [ 12   0   0   0   2   0   0]
 [  4   0   0   0   0   0   0]
 [  1   0   0   1   0   0   0]]
Accuracy Score : 0.9350046425255338


In [30]:
# SVM on Word Level TF IDF Vectors
accuracy = train_model(svm.SVC(), xtrain_tfidf, train_y, xvalid_tfidf)
print ("SVM, WordLevel TF-IDF: ", accuracy)
classifier = svm.SVC()

model = classifier.fit(xtrain_tfidf,train_y)

pred_y = model.predict(xvalid_tfidf)
results = confusion_matrix(valid_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(valid_y, pred_y))

SVM, WordLevel TF-IDF:  0.9415041782729805
Confusion Matrix :
[[606   0   0  16   0   0   0]
 [  7  11   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [ 25   0   0 391   0   0   0]
 [  9   0   0   0   5   0   0]
 [  3   0   0   0   0   1   0]
 [  1   0   0   1   0   0   0]]
Accuracy Score : 0.9415041782729805


In [31]:
# RF on Word Level TF IDF Vectors
accuracy = train_model(ensemble.RandomForestClassifier(), xtrain_tfidf, train_y, xvalid_tfidf)
print ("RF, WordLevel TF-IDF: ", accuracy)
classifier = ensemble.RandomForestClassifier()

model = classifier.fit(xtrain_tfidf,train_y)

pred_y = model.predict(xvalid_tfidf)
results = confusion_matrix(valid_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(valid_y, pred_y))

RF, WordLevel TF-IDF:  0.9322191272051996
Confusion Matrix :
[[591   0   0  31   0   0   0]
 [  6  12   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [ 22   0   0 394   0   0   0]
 [  9   0   0   0   5   0   0]
 [  4   0   0   0   0   0   0]
 [  1   0   0   1   0   0   0]]
Accuracy Score : 0.9303621169916435


In [37]:
# saving and Loading the model
# SVM
import pickle,joblib

In [39]:
# SVM on Word Level TF IDF Vectors
accuracy = train_model(svm.SVC(), xtrain_tfidf, train_y, xvalid_tfidf)
print ("SVM, WordLevel TF-IDF: ", accuracy)
classifier = svm.SVC()

model = classifier.fit(xtrain_tfidf,train_y)

pred_y = model.predict(xvalid_tfidf)
results = confusion_matrix(valid_y, pred_y) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(valid_y, pred_y))

SVM, WordLevel TF-IDF:  0.9415041782729805
Confusion Matrix :
[[606   0   0  16   0   0   0]
 [  7  11   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [ 25   0   0 391   0   0   0]
 [  9   0   0   0   5   0   0]
 [  3   0   0   0   0   1   0]
 [  1   0   0   1   0   0   0]]
Accuracy Score : 0.9415041782729805


In [38]:
tfidf = 'tfidf.pkl'
joblib.dump(tfidf_vect,tfidf)

['tfidf.pkl']

In [40]:
file_name = "modelsvm.pkl"
joblib.dump(model,file_name)

['modelsvm.pkl']

In [42]:
# Load tfidf from file
joblib_tfidf = joblib.load(tfidf)

In [43]:
# Load model from file
joblib_model = joblib.load(file_name)

In [48]:
# 
data_frame_test = pd.read_csv("unknown_articles.csv",encoding='latin1')

In [52]:
data_frame_test['Article.URL'][0]

'http://australianaviation.com.au/2018/10/a-competitive-edge-50-years-of-the-australian-army-aviation-corps/'

In [57]:
import requests
from bs4 import BeautifulSoup 

In [65]:
resp = requests.get(data_frame_test['Article.URL'][0])

In [72]:
soup=BeautifulSoup(resp.text,'html.parser')

In [74]:
print(soup.prettify)

<bound method Tag.prettify of <!DOCTYPE html>

<html lang="en-AU">
<head><style>img.lazy{min-height:1px}</style><link as="script" href="https://australianaviation.com.au/wp-content/plugins/w3-total-cache/pub/js/lazyload.min.js" rel="preload"/>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/><script type="text/javascript">(window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:false}};(window.NREUM||(NREUM={})).loader_config={xpid:"VQEPUFVRABAHVlNTDgMEUVM=",licenseKey:"37111ad895",applicationID:"722192377"};window.NREUM||(NREUM={}),__nr_require=function(t,e,n){function r(n){if(!e[n]){var i=e[n]={exports:{}};t[n][0].call(i.exports,function(e){var i=t[n][1][e];return r(i||e)},i,i.exports)}return e[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var i=0;i<n.length;i++)r(n[i]);return r}({1:[function(t,e,n){function r(t){try{c.console&&console.log(t)}catch(e){}}var i,o=t("ee"),a=t(23),c={};try{i=localStorage.getItem("__nr_flags").split(",

In [81]:
test = ["""
Bell Helicopters Textron, one of the companies behind the V-22 Osprey and the makers of a proposed Army tilt-rotor, are pitching a new drone for the Navy and Marine Corps that packs tilt-rotor technology into a large drone capable of carrying weapons, sensor platforms, and other payloads into combat.

The Bell V-247 Vigilant is to be an unmanned bird capable of operating at ranges of 1,300 nautical miles from its ship or base, carrying 2,000 pounds internally or a 9,000-pound sling load, or spending 12 hours time on station.

Of course, those numbers represent maximum endurance, maximum lift, or maximum range. A more likely mission profile combines all three. Bell says the aircraft will be capable of carrying a 600-pound payload 450 nautical miles for a mission with 8 hours time on station. It can also refuel in flight, further extending ranges and time on target.
And, with just two V-247s, a commander could establish 24-hour persistent reconnaissance of a target. That implies a much lower set of maintenance requirements than manned aircraft, since many require more hours of maintenance on the ground than they get in-flight hours.

Best of all, because the wings fold and it doesn't need space for a crew, the V-247 would fit in about the same amount of space on a ship as a UH-1Y, tight enough for it to land on Navy destroyers, whether to shuttle supplies or to refuel and re-arm for another mission.
For armament, Bell highlights its ability to fire air-to-surface missiles, helping Marines on the ground or potentially helping interdict fast boats during a swarm attack on the water.

All in, the design has a lot of the numbers that planners would want to see in a support aircraft. And, because it doesn't require a pilot, it can do a lot of complicated tasks while reducing the workload of the military's already strained pilot population. It's easy to see a role for an aircraft like this in fleet replenishment, in amphibious assault and air support, and in ship-to-shore logistics.
But, the Navy and Marine Corps are already on the hook for a large number of V-22 Ospreys. The Marine Corps has made the V-22 one of its most numerous aircraft, flying them across the world. And the Navy is looking to buy 38 V-22s to conduct fleet replenishment missions around the world, ferrying everything from engines to potatoes from warehouses on land to ships at sea.

So, while it would be useful for the Navy to get some smaller, unmanned aircraft to move the smaller packages between ships — especially since V-22 exhaust is so hot and fast-moving that it breaks down ship decks faster than other aircraft — there may not be enough money to go around. But the V-247 might represent a valuable asset for the Marines and Navy. And many of the sea services' missions for the tilt-rotor would be valuable for the Army as well.
"""] 

In [102]:
test_tdidf = joblib_tfidf.transform(test)

In [103]:
pred_test = joblib_model.predict(test_tdidf)

In [104]:
pred_test

array([3])

In [106]:
if pred_test[0] == 0:
    print("Article Type is Commercial")
elif pred_test[0] == 1:
    print("Article Type is Executives")
elif pred_test[0] == 2:
    print("Article Type is Military")
elif pred_test[0] == 3:
    print("Article Type is Others")
elif pred_test[0] == 4:
    print("Article Type is Support & Services")
elif pred_test[0] == 5:
    print("Article Type is Training")
else:
    print("Article Type is Unkonwn")

Article Type is Others
